"""chat_message table

Revision ID: 63f066e7ef14
Revises: ef43338ee15a
Create Date: 2026-09-05 13:52:35.635180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63f066e7ef14'
down_revision: Union[str, Sequence[str], None] = 'ef43338ee15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatMessage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('articleId', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('toolCalls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ChatMessage_articleId_idx', 'ChatMessage', ['articleId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ChatMessage_articleId_idx', table_name='ChatMessage')
    op.drop_table('ChatMessage')
    # ### end Alembic commands ###
